baseurl = "https://dawehner.github.io/"
languageCode = "en-us"
title = "Daniel Wehner's blog"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 42
paginate = 20
pygmentsCodefences = true
pygmentsStyle = "native"
RSSLink = "feed.xml"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug"
    book = "/books/:slug"
    page = "/:slug/"
    shader = "/shaders/:slug"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = -100

[[menu.main]]
    name = "Media"
    url = "/media"
    weight = -100

# [[menu.main]]
#     name = "Categories"
#     url = "/categories"
#     weight = -130

[params]
  description = ""
BooksSection = ["books"]

[params.logo]
url = "logo.png"
width = 50
height = 50
alt = "Logo"

[outputs]
home = ["RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe= true