RSSLink = "feed.xml"
baseurl = "https://daniel.town"
languageCode = "en-us"
paginate = 20
preserveTaxonomyNames = true
pygmentsCodefences = true
pygmentsStyle = "native"
rssLimit = 42
theme = "hugo-natrium-theme"
title = "Daniel Wehner's blog"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "About"
url = "/about/"
weight = -110

[[menu.main]]
name = "Projects"
url = "/projects"
weight = -100

[[menu.main]]
name = "Boardgames"
url = "/boardgame"
weight = -100

[[menu.main]]
name = "Media"
url = "/media"
weight = -100

[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"

[outputs]
home = ["RSS", "HTML"]

[params]
BooksSection = ["books"]
description = ""
mainSections = ["post", "book", "link", "boardgame", "shader"]

[params.logo]
alt = "Logo"
height = 50
url = "logo.png"
width = 50

[permalinks]
boardgame = "/boardgame/:slug"
book = "/books/:slug"
link = "/:slug"
page = "/:slug/"
post = "/:slug"
shader = "/shaders/:slug"

[taxonomies]
category = "categories"
tag = "tags"
