backend:
  branch: master
  name: github
  repo: dawehner/dawehner.github.com.source
  site_domain: daniel.town
collections:
  - create: true
    fields:
      - default: post
        label: Layout
        name: layout
        required: true
        widget: hidden
      - default: ''
        label: Title
        name: title
        required: true
        widget: string
      - default: ''
        label: Publish Date
        name: date
        required: true
        widget: datetime
      - default: ''
        label: Featured Image
        name: thumbnail
        required: false
        widget: image
      - default: ''
        label: Body
        name: body
        required: true
        widget: markdown
    folder: content/post
    label: Post
    name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - create: true
    fields:
      - default: post
        label: Layout
        name: layout
        required: true
        widget: hidden
      - default: ''
        label: Title
        name: title
        required: true
        widget: string
      - default: ''
        label: Publish Date
        name: date
        required: true
        widget: datetime
      - default: ''
        label: Link URL
        name: link_url
        required: true
        widget: string
      - default: ''
        label: Notes
        name: body
        required: true
        widget: markdown
    folder: content/link
    label: Link
    name: link
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - create: true
    fields:
      - default: book
        label: Layout
        name: layout
        required: true
        widget: hidden
      - default: ''
        label: Title
        name: title
        required: true
        widget: string
      - default: ''
        label: Publish Date
        name: date
        required: true
        widget: datetime
      - default: ''
        label: Featured Image
        name: thumbnail
        required: false
        widget: image
      - default: ''
        label: Body
        name: body
        required: true
        widget: markdown
    folder: content/media
    label: Book
    name: book
    slug: "{{year}}-{{slug}}"
  - create: true
    fields:
      - default: shader
        label: Layout
        name: layout
        required: true
        widget: hidden
      - default: ''
        label: Title
        name: title
        required: true
        widget: string
      - default: ''
        label: Publish Date
        name: date
        required: true
        widget: datetime
      - default: |
          {{< shader >}}
          
          {{< /shader >}}
          
        label: Body
        name: body
        required: true
        widget: markdown
    folder: content/shader
    label: Shader
    name: shader
    slug: "{{year}}-{{slug}}"
media_folder: static/img/uploads
public_folder: /img/uploads
publish_mode: editorial_workflow
