name: "Deploy blog"
on:
  pull_request:
  push:
jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}


    - uses: actions/checkout@v1
    - run: git submodule update --init
    - run: git submodule foreach git pull origin master
    - uses: cachix/install-nix-action@v12
      name: Install nix
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: make deploy-action
