name: "Deploy blog k8s"
on:
  push:
    branches:
      - main
jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}


    - uses: actions/checkout@v1
      name: Check out code
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: true
